source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SpeedLog_Example', :exclusive => true do
  pod "SpeedLog", :path => "../"
end

target 'SpeedLog_Tests', :exclusive => true do
  pod "SpeedLog", :path => "../"

  
end
